version: '3.9'
services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: 'metastore_db'
      POSTGRES_USER: 'hive'
      POSTGRES_PASSWORD: 'password'
    ports:
      - '5432:5432'
    volumes:
      - ./volumes/hive_db:/var/lib/postgresql/data
    networks:
      - hive

  metastore:
    image: apache/hive:${HIVE_VERSION}
    depends_on:
      - postgres
    container_name: metastore
    hostname: metastore
    environment:
      DB_DRIVER: postgres
      SERVICE_NAME: 'metastore'
      SERVICE_OPTS: '-Xmx1G -Djavax.jdo.option.ConnectionDriverName=org.postgresql.Driver
                     -Djavax.jdo.option.ConnectionURL=jdbc:postgresql://postgres:5432/metastore_db
                     -Djavax.jdo.option.ConnectionUserName=hive
                     -Djavax.jdo.option.ConnectionPassword=password'
    ports:
        - '9083:9083'
    volumes:
        - ./volumes/warehouse:/opt/hive/data/warehouse
        - ./lib/postgresql.jar:/opt/hive/lib/postgresql.jar
    networks:
      - hive

  hiveserver2:
    image: apache/hive:${HIVE_VERSION}
    depends_on:
      - metastore
    container_name: hiveserver2
    environment:
      HIVE_SERVER2_THRIFT_PORT: 10000
      SERVICE_OPTS: '-Xmx1G -Dhive.metastore.uris=thrift://metastore:9083'
      SERVICE_NAME: 'hiveserver2'
      IS_RESUME: "true"
    ports:
      - '10000:10000'
      - '10002:10002'
    volumes:
      - ./volumes/warehouse:/opt/hive/data/warehouse
      - ./lib/postgresql.jar:/opt/hive/lib/postgresql.jar
    networks:
      - hive

  superset:
    image: apache/superset:latest
    depends_on:
      - postgres
    container_name: superset
    hostname: superset
    environment:
      SUPERSET_SECRET_KEY: 'your-secret-key-here'
      # DATABASE_URL: 'postgresql://hive:password@postgres:5432/metastore_db'
      SUPERSET_LOAD_EXAMPLES: 'yes'
    ports:
      - '8088:8088'
    networks:
      - hive
    command: >
      bash -c "
      superset db upgrade &&
      pip install pyhive thrift sqlalchemy PyHive thrift_sasl &&
      superset fab create-admin --username admin --firstname Admin --lastname User --email admin@example.com --password admin &&
      superset init &&
      superset run -h 0.0.0.0 -p 8088
      "
  
  # pipeline:
  #   build: ./src
  #   container_name: pipeline
  #   volumes:
  #     - ./src/data:/app/data
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   networks:
  #     - hive
networks:
  hive:
    name: hive
    driver: bridge